- name: Deploy a Mysql DB Server
  hosts: targetserver1
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - common
    - mysql_db

- name: Deploy a Web Application Server
  hosts: targetserver2
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - common
    - flask_web